config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  root "pages#home"

  resources :articles

  resources :users, except: [:new]

  get "signup", to: "users#new"

  get "signin", to: "sessions#new"

  post "signin", to: "sessions#create"

  get "logout", to: "sessions#destroy"

  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 5
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 4, maximum: 20}
  validates :description, presence: true, length: {minimum: 5, maximum: 1000}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  before_save {self.email = email.downcase}
  paginates_per 5
  has_many :articles
  # VALID_EMAIL_REGEX = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/
  validates :username, presence: true, length: {minimum: 3, maximum: 20}, uniqueness: true
  validates :email, presence: true, length: {minimum: 15, maximum: 40}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in"
      redirect_to signin_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :require_user, only: [:show, :edit, :new, :create, :update, :destroy]
  before_action :article_find_by_id, only: [:show, :edit, :update, :destroy]
  before_action :article_params, only: [:create, :update]

  def index
    @articles = Article.all.page(params[:page])
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article has been created successfully"
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article has been edited successfully"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = "Article has been deleted successfully"
      redirect_to articles_path
    end
  end

  private

    def article_find_by_id
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_category_by_id, only: [:show, :edit, :update, :destroy]
  before_action :category_params, only: [:create, :update]

  def index
    @categories = Category.all
  end

  def show

  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category has been created successfully"
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category has been updated successfully"
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = "Category has been deleted successfully"
      redirect_to categories_path
    end
  end


  private

    def find_category_by_id
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user and user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have been logged in successfully"
      redirect_to articles_path
    else
      flash[:error] = "Email or Password is invalid"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, only: [:show, :edit, :update, :destroy]
  before_action :find_user_by_id, only: [:show, :edit, :update, :destroy]
  before_action :user_params, only: [:create, :update]

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @articles = @user.articles
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User has been created successfully"
      session[:user_id] = @user.id
      redirect_to signin_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User has been updated successfully"
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      flash[:success] = "User has been deleted successfully"
      redirect_to articles_path
    end
  end

  private

    def find_user_by_id
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>

  <%= render "notifications/errors", obj: @article %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", id: "exampleFormControlInput1", placeholder: "Enter article's title" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", id: "exampleFormControlTextarea1", rows: "3", placeholder: "Enter article's description" %>
  </div>

  <div class="mb-3">
    <%= form.label :categories, class: "form-label" %>
    <%= form.collection_select(:category_ids, Category.all, :id, :name, {promt: "Select multiple categories"}, {multiple: true, class: "form-select", id: "exampleFormControlTextarea1", rows: "3"}) %>
  </div>

  <div class="text-center">
    <%= form.submit(@article.new_record? ? "Create" : "Edit", class: "btn btn-outline-primary") %>
  </div>

<%end%>

app/views/articles/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">Edit article</h1>
    <%= render "form" %>
  </div>
</div>

app/views/articles/index.html.erb
<%= render "notifications/success" %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">List of articles</h1>
    <% @articles.each do |article| %>
      <div class="card text-center my-3">
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
          <% if article.categories.any? %>
            <div class="my-2">
              Categories:
              <% article.categories.each do |category| %>
                <span class="badge rounded-pill text-bg-info"><%= category.name %></span>
              <%end%>
            </div>
          <%end%>
          <p class="card-text"><%= truncate(article.description, length:150) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-success" %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-primary" %>
          <%= link_to "Delete", article_path(article), data: {turbo_method: :delete}, class: "btn btn-danger" %>
        </div>
        <div class="card-footer text-muted">
          created at <%= article.created_at.year %>-<%= article.created_at.month %>-<%= article.created_at.day %> and updated at <%= article.updated_at.year %>-<%= article.updated_at.month %>-<%= article.updated_at.day %>
        </div>
      </div>
    <% end %>

    <%= paginate @articles %>

  </div>
</div>

app/views/articles/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">Create new article</h1>
    <%= render "form" %>
  </div>
</div>

app/views/articles/show.html.erb
<%= render "notifications/success" %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4"><%= @article.title %></h1>
    <div class="card text-center">
      <div class="card-header">
        <%= image_tag @article.user.gravatar_url %>
        <br>
        <%= link_to @article.user.username, user_path(@article.user) %>
        <% if @article.categories.any? %>
          <div class="my-2">
            Categories:
            <% @article.categories.each do |category| %>
              <span class="badge rounded-pill text-bg-info"><%= category.name %></span>
            <%end%>
          </div>
        <%end%>
      </div>
      <div class="card-body">
        <p class="card-text text-start"><%= @article.description %></p>

        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary" %>
        <%= link_to "Delete", article_path(@article), data: {turbo_method: :delete}, class: "btn btn-danger" %>
      </div>
      <div class="card-footer text-muted">
        created at <%= @article.created_at.year %>-<%= @article.created_at.month %>-<%= @article.created_at.day %> and updated at <%= @article.updated_at.year %>-<%= @article.updated_at.month %>-<%= @article.updated_at.day %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: @category) do |form| %>

  <%= render "notifications/errors", obj: @category %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", id: "exampleFormControlInput1", placeholder: "Enter category name" %>
  </div>

  <div class="text-center">
    <%#= form.submit(@category.new_record? ? "Create" : "Edit", class: "btn btn-outline-primary") %>
    <%= form.submit "Create", class: "btn btn-outline-primary" %>
  </div>

<%end%>

app/views/categories/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">Edit category</h1>
    <%= render "form" %>
  </div>
</div>

app/views/categories/index.html.erb
<%= render "notifications/success" %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">List of articles</h1>
    <% @categories.each do |category| %>
      <div class="card text-center my-3">
        <div class="card-body">
          <h5 class="card-title"><%= link_to category.name, category_path(category) %></h5>
          <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          <%= link_to "View", category_path(category), class: "btn btn-success" %>
          <%= link_to "Edit", edit_category_path(category), class: "btn btn-primary" %>
          <%= link_to "Delete", category_path(category), data: {turbo_method: :delete}, class: "btn btn-danger" %>
        </div>
        <div class="card-footer text-muted">
          created at <%= category.created_at.year %>-<%= category.created_at.month %>-<%= category.created_at.day %> and updated at <%= category.updated_at.year %>-<%= category.updated_at.month %>-<%= category.updated_at.day %>
        </div>
      </div>
    <% end %>

    <%#= paginate @articles %>

  </div>
</div>

app/views/categories/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">Create new category</h1>
    <%= render "form" %>
  </div>
</div>

app/views/categories/show.html.erb
<%= render "notifications/success" %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4"><%= @category.name %></h1>
    <div class="card text-center">
      <div class="card-body">
        <p class="card-text text-start"><%= @category.name %></p>
        <%= link_to "Edit", edit_category_path(@category), class: "btn btn-primary" %>
        <%= link_to "Delete", category_path(@category), data: {turbo_method: :delete}, class: "btn btn-danger" %>
      </div>
      <div class="card-footer text-muted">
        created at <%= @category.created_at.year %>-<%= @category.created_at.month %>-<%= @category.created_at.day %> and updated at <%= @category.updated_at.year %>-<%= @category.updated_at.month %>-<%= @category.updated_at.day %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to "ALPHA-BLOG", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Articles", articles_path, class: "dropdown-item" %>
            <%= link_to "Create-Article", new_article_path, class: "dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Categories", categories_path, class: "dropdown-item" %>
            <% if logged_in? and current_user.is_admin? %>
              <%= link_to "Create-Category", new_category_path, class: "dropdown-item" %>
            <%end%>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Users
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Users", users_path, class: "dropdown-item" %>
            <%= link_to "Create-User", signup_path, class: "dropdown-item" %>
          </ul>
        </li>
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "[ #{current_user.username} ]", user_path(current_user), class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link active" %>
            </li>
          <%else%>
            <li class="nav-item">
              <%= link_to "Signin", signin_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Signup", signup_path, class: "nav-link active" %>
            </li>
          <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha-Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notifications/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<%end%>

app/views/notifications/_success.html.erb
<div class="row">
    <% if flash[:success] %>
      <div class="alert alert-success alert-dismissible fade show my-4" role="alert">
        <ul>
          <li><%= flash[:success] %></li>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </ul>
      </div>
    <%end%>
</div>

app/views/pages/home.html.erb
<div class="row justify-content-center mt-5">
  <div class="col-md-12">
    <div class="slider">
<!--      <img src="../../assets/images/slider1.jpg" class="img-fluid" alt="slider1">-->
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>

  <%= render "notifications/errors", obj: @user %>

  <div class="mb-3">
    <%= form.label :username, class: "form-label" %>
    <%= form.text_field :username, class: "form-control", id: "exampleFormControlInput1", placeholder: "Enter your username" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control", id: "exampleFormControlTextarea1", placeholder: "Enter your email" %>
  </div>

  <div class="mb-3">
    <%= form.label :password, class: "form-label" %>
    <%= form.password_field :password, class: "form-control", id: "exampleFormControlTextarea1", placeholder: "Enter your password" %>
  </div>

  <div class="text-center">
    <%= form.submit(@user.new_record? ? "Signup" : "Edit", class: "btn btn-outline-primary") %>
  </div>

<%end%>

app/views/users/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">Edit profile</h1>
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<%= render "notifications/success" %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">List of users</h1>
    <% @users.each do |user| %>
      <div class="card text-center my-3">
        <div class="card-header">
          <%= link_to user.username, user_path(user) %>
        </div>
        <div class="card-body">
          <%= image_tag user.gravatar_url %>
          <h5 class="card-title"><%= link_to user.username, user_path(user) %></h5>
          <p class="card-text"><%= user.email %></p>
          <%= link_to "View", user_path(user), class: "btn btn-success" %>
          <%= link_to "Edit", edit_user_path(user), class: "btn btn-primary" %>
          <%= link_to "Delete", user_path(user), data: {turbo_method: :delete}, class: "btn btn-danger" %>
        </div>
        <div class="card-footer text-muted">
          created at <%= user.created_at.year %>-<%= user.created_at.month %>-<%= user.created_at.day %> and updated at <%= user.updated_at.year %>-<%= user.updated_at.month %>-<%= user.updated_at.day %>
        </div>
      </div>
    <% end %>

    <%= paginate @users %>

  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4">Create new user</h1>
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "notifications/success" %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center my-4"><%= @user.username %></h1>
    <div class="card text-center">
      <div class="card-header">
        <%= link_to @user.username, user_path(@user) %>
      </div>
      <div class="card-body">
        <%= image_tag @user.gravatar_url %>
        <p class="my-2"><span class="badge text-bg-<%= @user.is_admin? ? "success" : "danger" %>">Admin</span></p>
        <p class="card-text"><%= @user.email %></p>
        <p><%= pluralize(@articles.count, "article") %></p>
        <%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %>
        <%= link_to "Delete", user_path(@user), data: {turbo_method: :delete}, class: "btn btn-danger" %>
      </div>
      <div class="card-footer text-muted">
        created at <%= @user.created_at.year %>-<%= @user.created_at.month %>-<%= @user.created_at.day %> and updated at <%= @user.updated_at.year %>-<%= @user.updated_at.month %>-<%= @user.updated_at.day %>
      </div>
    </div>
  </div>

  <div class="col-md-8 my-4">
    <h1 class="text-center my-4">List of articles for <%= @user.username %></h1>
    <% @articles.each do |article| %>
      <div class="card text-center my-3">
        <div class="card-header">
          <%= article.user.username %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
          <p class="card-text"><%= truncate(article.description, length:150) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-success" %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-primary" %>
          <%= link_to "Delete", article_path(article), data: {turbo_method: :delete}, class: "btn btn-danger" %>
        </div>
        <div class="card-footer text-muted">
          created at <%= article.created_at.year %>-<%= article.created_at.month %>-<%= article.created_at.day %> and updated at <%= article.updated_at.year %>-<%= article.updated_at.month %>-<%= article.updated_at.day %>
        </div>
      </div>
    <% end %>
  </div>

</div>